In [1]:
import torch
import numpy as np
import time

In [2]:
randint = torch.randint(-100,100,(6,))
randint

tensor([ 61, -85, -28,  41,  53, -65])

In [3]:
tensor = torch.tensor([[0.1,0.2],[2.2,3.0],[4.9,6.1]])
tensor

tensor([[0.1000, 0.2000],
        [2.2000, 3.0000],
        [4.9000, 6.1000]])

In [4]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3,2)
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [6]:
input = torch.empty(2,3)
input

tensor([[1.7312e-34, 4.3316e-41, 6.7705e+13],
        [3.3099e-41, 1.4013e-45, 0.0000e+00]])

In [7]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [8]:
linspace = torch.linspace(3,10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
logspace = torch.logspace(start=-10, end=10, steps= 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [10]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
print(a)
print(empty_like)

tensor([[132761858219168, 101448578185680,               1],
        [101448578192304,               0,               0]])
tensor([[              0,               0, 101448578189072],
        [101448550932672, 132760158953984,               0]])


In [12]:
#measuring compute time
start_time = time.time()
zeros = torch.zeros(2,2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.4f}")


#Computation for tensors 
torch_rand1 = torch.rand(100,100,100,100)
torch_rand2 = torch.rand(100,100,100,100)
np_rand1 = torch.rand(100,100,100,100)
np_rand2 = torch.rand(100,100,100,100)

start_time = time.time()
rand = (torch_rand1 @ torch_rand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.0007
0.53916407
0.46342087


In [13]:
# Probability Tensor
# sum of values inside the array should be equal to 1
probabilities = torch.tensor([0.1,0.9])
# 10% or 0.1 =>0 implies 0 has a probability of 10%
#Draw 5 samples from multinomial distribution
samples = torch.multinomial(probabilities, num_samples = 10, replacement = True)
print(samples)

tensor([1, 1, 0, 1, 1, 1, 1, 1, 0, 1])


In [14]:
# Concatenate 2 tensors
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim = 0)
out

tensor([1, 2, 3, 4, 5])

In [15]:
#Tril means triangle lower
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [16]:
# Triu means Triangle Upper
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [17]:
#This is like log of each element. Log 1 = 0, log 0 = -inf
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [18]:
# opp of log
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [19]:
input = torch.zeros(2,3,4)
# Here 0,2 means 0th position is swapped with 2nd position
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [20]:
# Stacking increases dimensions
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])
stacked_tensor = torch.stack([tensor1,tensor2,tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [21]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3, bias=False)
print(linear)
print(linear(sample))

Linear(in_features=3, out_features=3, bias=False)
tensor([ 2.6823,  2.2428, -4.5170], grad_fn=<SqueezeBackward4>)


In [22]:
#Softmax function
import torch.nn.functional as F

#create a tensor
tensor1 = torch.tensor([1.0,2.0,3.0])
#Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [23]:
#Embeddings - basically a numerical representation of a character

vocab_size = 100
embedding_dim = 14
embedding = nn.Embedding(vocab_size, embedding_dim)

#Input indices
input_indices = torch.LongTensor([1,5,3,2])
embedded_output = embedding(input_indices)
print(embedded_output)
print(embedded_output.shape)



tensor([[-0.7528,  0.5889, -0.7046,  1.8386,  0.7168, -0.9597,  1.1684, -1.3400,
         -3.1730,  0.4389,  0.1517, -1.2415,  0.1340, -0.1760],
        [-0.1783, -1.4052, -0.9768, -0.6623,  0.1564,  0.3587, -1.2790,  1.6250,
         -0.0981,  1.0592,  0.6075, -0.4876,  0.5329, -0.8103],
        [ 1.4383, -0.0260,  0.0407, -0.0684, -0.7262, -0.7680, -1.1744,  0.7945,
         -1.3999, -0.2500,  1.0284,  2.0953,  0.7545,  0.2710],
        [ 0.5126, -1.2689, -0.4142,  0.2739,  0.2465,  0.3592, -0.7877,  0.5784,
         -0.1059, -1.1665,  0.1746, -0.8049, -0.4836,  0.2754]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([4, 14])


In [24]:
#Matrix multiplication
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a@b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [25]:
#Only same data type can be multiplied.
# Integer needs to be explicitly converted to float before multiplication

int_64 = torch.randint(1,(3,2)).float()
# 1 means the range 0-1, 3,2 means the dimensions of the matrix
float_32 = torch.rand(2,3)
print(int_64 @ float_32)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
